spring.application.name=restful-web-services
logging.level.org.springframework=info
  
#expose all apis
management.endpoints.web.exposure.include=* 
     
#Configuration for H2 in-memory-database
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.show-sql=true

#Configuration of MySQL relational Database
spring.datasource.url=jdbc:mysql://localhost:3306/social_media_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


app.jwt-secret=9327cf705fde1eab2b91fb1c5646f36eb334476ff40b3de9935ac9ad9c8849c4
app.jwt-expiration-milliseconds=604800000




#Authorization configuration
#spring.security.user.name=username
#spring.security.user.password=password


spring.messages.encoding=UTF-8


# versioning using Spring Boot versioning
#spring.mvc.apiversion.use.path-segment=0
#spring.mvc.apiversion.use.query-parameter=version
#spring.mvc.apiversion.use.header=X-API-VERSION

#spring.mvc.apiversion.use.media-type-parameter[application/json]=version